apiVersion: v1
kind: Pod
metadata:
  name: git-sync-test
spec:
  containers:
  ###########################
  # 첫번째, 메인 컨테이너
  ###########################
  - name: ubuntu
    image: ubuntu:18.04
    args:
    - sleep
    - "10000000000000"
    volumeMounts:
    - name: mygit
      mountPath: "/git"
  ###########################
  # 두번째, 사이드카 컨테이너
  ###########################
  - name: git-sync
    image: k8s.gcr.io/git-sync/git-sync:v3.2.2
    args:
      - "--ssh"
      - "--repo=git@github.kakaocorp.com:addy-b/airflow-dag-script.git"
      - "--root=/git"
      - "--branch=master"
      - "--dest=dags"
      - "--depth=1"
    volumeMounts:
    - name: mygit
      mountPath: "/git"
    - name: git-secret
      mountPath: "/etc/git-secret"
  restartPolicy: Never

  # 서로 연결할 volume
  volumes:
  - name: mygit
    emptyDir: {}
  - name: git-secret
    secret:
      secretName: git-creds
      defaultMode: 0444
